name: Sulphur
version: ${project.version}
main: org.zafire.sulphur.SulphurPlugin
api: 1.8.8
author: ZetaStormy
description: Provides a powerful core for Survival server of ZafireNT.
depend: [PlaceholderAPI, Boss, Vault, NBTAPI, HamsterAPI]

commands:
  Lobby:
    usage: /<command>
    aliases: [hub]
    description: Travel to the lobby server of LiteriumNT.
  Store:
    usage: /<command>
    aliases: [tienda]
    description: A command to get the store of LiteriumNT.
  Discord:
    usage: /<command>
    aliases: []
    description: A command to get the discord of LiteriumNT.    
  Boss:
    usage: /<command> time
    aliases: [jefe]
    description: A command to get the time left for the boss.
  Sulphur:
    usage: /<command>
    description: Main command of the Sulphur core.